#commentatio

name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   
  pruebas-unitarias:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - name: Unit Tests
        run: mvn test | netstat -an

  empaquetar:
    runs-on: self-hosted
    needs: pruebas-unitarias
    steps:
      - name: build
        run: mvn package -DskipTests=true | netstat -an
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: baloncesto
          path: target/

  pruebas-funcionales:
    runs-on: self-hosted
    needs: empaquetar
    steps:
      - run: netstat -an
      - run: cp -r target/Baloncesto /usr/local/tomcat/webapps
      - run: netstat -an
      - run: mysql -u root < db/baloncesto.sql
      - run: netstat -an
      - run: export DATABASE_HOST="jdbc:mysql://localhost"
      - run: netstat -an
      - run: export DATABASE_PORT="3306"
      - run: netstat -an
      - run: export DATABASE_NAME="baloncesto"
      - run: netstat -an
      - run: export DATABASE_USER="usuario"
      - run: netstat -an
      - run: export DATABASE_PASS="clave"
      - run: netstat -an
      - run: sh /usr/local/tomcat/bin/catalina.sh stop
      - run: netstat -an
      - run: sh /usr/local/tomcat/bin/catalina.sh start
      - run: netstat -an

      #- run: mvn failsafe:integration-test failsafe:verify


  #qa:
    #runs-on: self-hosted
    #needs: empaquetar
    #steps:
      #- run: echo "qa step"

  #release:
    #runs-on: self-hosted
    #needs: empaquetar
    #steps:
      #- run: echo "release step"

  #deploy:
    #runs-on: self-hosted
    #needs: empaquetar
    #steps:
      #- run: echo "deploy step"