#commentario

name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   
  pruebas-unitarias:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - run: mvn test

  empaquetar:
    runs-on: self-hosted
    needs: pruebas-unitarias
    steps:
      - name: build
        run: mvn package -DskipTests=true
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: baloncesto
          path: target/

  pruebas-funcionales:
    runs-on: self-hosted
    needs: empaquetar
    steps:
      - name: prueba
        run: |
          cp -r target/Baloncesto /usr/local/tomcat/webapps
      - name: prueba2
        run: |
          sh /usr/local/tomcat/bin/catalina.sh stop
          mysql -u root < db/baloncesto.sql
          export DATABASE_HOST="jdbc:mysql://localhost"
          export DATABASE_PORT="3306"
          export DATABASE_NAME="baloncesto"
          export DATABASE_USER="usuario"
          export DATABASE_PASS="clave"
          sh /usr/local/tomcat/bin/catalina.sh stop
          sh /usr/local/tomcat/bin/catalina.sh start
      #- run: mvn failsafe:integration-test failsafe:verify


  #qa:
    #runs-on: self-hosted
    #needs: empaquetar
    #steps:
      #- run: echo "qa step"

  #release:
    #runs-on: self-hosted
    #needs: empaquetar
    #steps:
      #- run: echo "release step"

  #deploy:
    #runs-on: self-hosted
    #needs: empaquetar
    #steps:
      #- run: echo "deploy step"