name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   
  pruebas-unitarias:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - name: Unit Tests
        run: netstat -an


  pruebas-funcionales:
    runs-on: self-hosted
    steps:
      - run: |
          netstat -an
          sh /usr/local/tomcat/bin/catalina.sh stop
          netstat -an
          sh /usr/local/tomcat/bin/catalina.sh start
          netstat -an

