#Comentario

name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   
        

  pruebas-unitarias:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - run: mvn test

  empaquetar:
    runs-on: self-hosted
    needs: pruebas-unitarias
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - name: build
        run: mvn package -DskipTests=true
        
  pruebas-funcionales:
    runs-on: self-hosted
    needs: empaquetar
    steps:
      - run: echo "test step"

  qa:
    runs-on: self-hosted
    needs: pruebas-funcionales
    steps:
      - run: echo "qa step"

  release:
    runs-on: self-hosted
    needs: qa
    steps:
      - run: echo "release step"

  deploy:
    runs-on: self-hosted
    needs: release
    steps:
      - run: echo "deploy step"